//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EfsaBusinessRuleValidator.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EfsaBusinessRuleValidator.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;&lt;areas&gt;&lt;area country=&quot;DZ&quot; code=&quot;DZG237852&quot; /&gt;&lt;area country=&quot;DZ&quot; code=&quot;DZG237854&quot; /&gt;&lt;area country=&quot;DZ&quot; code=&quot;DZG237872&quot; /&gt;&lt;area country=&quot;DZ&quot; code=&quot;DZG237873&quot; /&gt;&lt;area country=&quot;DZ&quot; code=&quot;DZG237877&quot; /&gt;&lt;area country=&quot;DZ&quot; code=&quot;DZG237878&quot; /&gt;&lt;area country=&quot;DZ&quot; code=&quot;DZG237898&quot; /&gt;&lt;area country=&quot;DZ&quot; code=&quot;DZG237906&quot; /&gt;&lt;area country=&quot;DZ&quot; code=&quot;DZG237915&quot; /&gt;&lt;area country=&quot;DZ&quot; code=&quot;DZG237920&quot; /&gt;&lt;area country=&quot;DZ&quot; code=&quot;DZG237923&quot; /&gt;&lt;area country=&quot;DZ&quot; code=&quot;DZG237926&quot; /&gt;&lt;area count [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Nuts_Rule_Check {
            get {
                return ResourceManager.GetString("Nuts_Rule_Check", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to prodCode,paramCode,parTyp
        ///P0100000A,RF-0001-001-PPP,P005A
        ///P0110000A,RF-0001-001-PPP,P005A
        ///P0110010A,RF-0001-001-PPP,P005A
        ///P0110020A,RF-0001-001-PPP,P005A
        ///P0110030A,RF-0001-001-PPP,P005A
        ///P0110040A,RF-0001-001-PPP,P005A
        ///P0110050A,RF-0001-001-PPP,P005A
        ///P0110990A,RF-0001-001-PPP,P005A
        ///P0120000A,RF-0001-001-PPP,P005A
        ///P0120010A,RF-0001-001-PPP,P005A
        ///P0120020A,RF-0001-001-PPP,P005A
        ///P0120030A,RF-0001-001-PPP,P005A
        ///P0120040A,RF-0001-001-PPP,P005A
        ///P0120050A,RF-0001-001-PPP,P005A
        ///P0120060A,RF-0001-001-P [rest of string was truncated]&quot;;.
        /// </summary>
        public static string tablea {
            get {
                return ResourceManager.GetString("tablea", resourceCulture);
            }
        }
    }
}
